//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelBook.Domain
{
    using Perfect.Event;
    using Perfect.Repository;
    using TelBook.Domain.Event;
    using System;
    using System.Collections.Generic;

    public partial class TelGroup : ModelBase
    {
        public void PreHandle(DeleteDomainObjectEvent evnt)
        {
            IRepository<Tel> repository = evnt.RepositoryContext.GetRepository<Tel>();
            var list = repository.Query(a => a.GroupID == this.ID);
            EventProcesser.ProcessEvent(list, new DeleteDomainObjectEvent());
        }
    }
}