//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfect.DesignByContract {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perfect.DesignByContract.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 断言失败 的本地化字符串。
        /// </summary>
        internal static string Error_AssertionFailed {
            get {
                return ResourceManager.GetString("Error_AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断言失败：{0} 的本地化字符串。
        /// </summary>
        internal static string Error_AssertionMessage {
            get {
                return ResourceManager.GetString("Error_AssertionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录“{0}”必须存在 的本地化字符串。
        /// </summary>
        internal static string Error_DirectoryPathMustBeExists {
            get {
                return ResourceManager.GetString("Error_DirectoryPathMustBeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有满足不变量 的本地化字符串。
        /// </summary>
        internal static string Error_InvariantFailed {
            get {
                return ResourceManager.GetString("Error_InvariantFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须满足不变量：{0} 的本地化字符串。
        /// </summary>
        internal static string Error_InvariantMessage {
            get {
                return ResourceManager.GetString("Error_InvariantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有满足后置条件 的本地化字符串。
        /// </summary>
        internal static string Error_PostconditionFailed {
            get {
                return ResourceManager.GetString("Error_PostconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须满足后置条件：{0} 的本地化字符串。
        /// </summary>
        internal static string Error_PostconditionMessage {
            get {
                return ResourceManager.GetString("Error_PostconditionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有满足条件失败 的本地化字符串。
        /// </summary>
        internal static string Error_PreconditionFailed {
            get {
                return ResourceManager.GetString("Error_PreconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须满足前置条件：{0} 的本地化字符串。
        /// </summary>
        internal static string Error_PreconditionMessage {
            get {
                return ResourceManager.GetString("Error_PreconditionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串{0} 不能为空或者空白 的本地化字符串。
        /// </summary>
        internal static string Error_TargetCanNotEmpty {
            get {
                return ResourceManager.GetString("Error_TargetCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0} 不能为空 的本地化字符串。
        /// </summary>
        internal static string Error_TargetCanNotNull {
            get {
                return ResourceManager.GetString("Error_TargetCanNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串{0} 不能为空或者空白 的本地化字符串。
        /// </summary>
        internal static string Error_TargetCanNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Error_TargetCanNotNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
